version: "3.7"
services:
  jakmat-api:
    build: .
    restart: always
    ports:
      - 5000:5000
    environment:
      - DEBUG=1
    networks:
      - flask_network
  proxy:
    build: proxy
    restart: always
    ports:
      - 80:80
    networks:
      - flask_network
networks:
  flask_network:
